#!/bin/sh
if [ "$(basename "$1")" != "$(basename "$1" .md)" ] \
    || [ "$(basename "$1")" != "$(basename "$1" .conf)" ] \
    || [ "$(basename "$1")" != "$(basename "$1" .dir)" ]
then
    echo "644"
    return 0
fi
echo "755"
return 0
